// AUTO-GENERATED from refs/claude-code/src/commands/ — see
// scripts/extract-claude-code-commands.mjs. Do not hand-edit; rerun the
// extractor when you sync the refs/ snapshot.
export type BuiltinSlash = {
  readonly name: string
  readonly description: string
  readonly aliases?: readonly string[]
}

export const BUILTIN_CLAUDE_SLASHES: readonly BuiltinSlash[] = [
  { name: "add-dir", description: "Add a new working directory" },
  { name: "advisor", description: "Configure the advisor model" },
  { name: "agents", description: "Manage agent configurations" },
  { name: "branch", description: "Create a branch of the current conversation at this point" },
  { name: "bridge-kick", description: "Inject bridge failure states for manual recovery testing" },
  { name: "brief", description: "Toggle brief-only mode" },
  { name: "btw", description: "Ask a quick side question without interrupting the main conversation" },
  { name: "chrome", description: "Claude in Chrome (Beta) settings" },
  { name: "clear", description: "Clear conversation history and free up context", aliases: ["reset", "new"] },
  { name: "color", description: "Set the prompt bar color for this session" },
  { name: "commit", description: "Create a git commit" },
  { name: "commit-push-pr", description: "Commit, push, and open a PR" },
  { name: "compact", description: "Clear conversation history but keep a summary in context. Optional: /compact [instructions for summarization]" },
  { name: "config", description: "Open config panel", aliases: ["settings"] },
  { name: "context", description: "Visualize current context usage as a colored grid" },
  { name: "copy", description: "Copy Claude's last response to clipboard (or /copy N for the Nth-latest)" },
  { name: "cost", description: "Show the total cost and duration of the current session" },
  { name: "desktop", description: "Continue the current session in Claude Desktop", aliases: ["app"] },
  { name: "diff", description: "View uncommitted changes and per-turn diffs" },
  { name: "doctor", description: "Diagnose and verify your Claude Code installation and settings" },
  { name: "effort", description: "Set effort level for model usage" },
  { name: "exit", description: "Exit the REPL", aliases: ["quit"] },
  { name: "export", description: "Export the current conversation to a file or clipboard" },
  { name: "extra-usage", description: "Configure extra usage to keep working when limits are hit" },
  { name: "fast", description: "" },
  { name: "feedback", description: "", aliases: ["bug"] },
  { name: "files", description: "List all files currently in context" },
  { name: "help", description: "Show help and available commands" },
  { name: "hooks", description: "View hook configurations for tool events" },
  { name: "ide", description: "Manage IDE integrations and show status" },
  { name: "init", description: "" },
  { name: "init-verifiers", description: "Create verifier skill(s) for automated verification of code changes" },
  { name: "install", description: "Install Claude Code native build" },
  { name: "install-github-app", description: "Set up Claude GitHub Actions for a repository" },
  { name: "install-slack-app", description: "Install the Claude Slack app" },
  { name: "keybindings", description: "Open or create your keybindings configuration file" },
  { name: "login", description: "" },
  { name: "logout", description: "Sign out from your Anthropic account" },
  { name: "mcp", description: "Manage MCP servers" },
  { name: "memory", description: "Edit Claude memory files" },
  { name: "mobile", description: "Show QR code to download the Claude mobile app", aliases: ["ios", "android"] },
  { name: "model", description: "" },
  { name: "passes", description: "" },
  { name: "permissions", description: "Manage allow & deny tool permission rules", aliases: ["allowed-tools"] },
  { name: "plan", description: "Enable plan mode or view the current session plan" },
  { name: "plugin", description: "Manage Claude Code plugins", aliases: ["plugins", "marketplace"] },
  { name: "pr-comments", description: "Get comments from a GitHub pull request" },
  { name: "privacy-settings", description: "View and update your privacy settings" },
  { name: "project_areas", description: "Generate a report analyzing your Claude Code sessions" },
  { name: "release-notes", description: "View release notes" },
  { name: "reload-plugins", description: "Activate pending plugin changes in the current session" },
  { name: "remote-control", description: "Connect this terminal for remote-control sessions", aliases: ["rc"] },
  { name: "remote-env", description: "Configure the default remote environment for teleport sessions" },
  { name: "rename", description: "Rename the current conversation" },
  { name: "resume", description: "Resume a previous conversation", aliases: ["continue"] },
  { name: "review", description: "Review a pull request" },
  { name: "rewind", description: "", aliases: ["checkpoint"] },
  { name: "sandbox", description: "" },
  { name: "security-review", description: "Complete a security review of the pending changes on the current branch" },
  { name: "session", description: "Show remote session URL and QR code", aliases: ["remote"] },
  { name: "skills", description: "List available skills" },
  { name: "stats", description: "Show your Claude Code usage statistics and activity" },
  { name: "status", description: "Show Claude Code status including version, model, account, API connectivity, and tool statuses" },
  { name: "statusline", description: "Set up Claude Code's status line UI" },
  { name: "stickers", description: "Order Claude Code stickers" },
  { name: "tag", description: "Toggle a searchable tag on the current session" },
  { name: "tasks", description: "List and manage background tasks", aliases: ["bashes"] },
  { name: "terminal-setup", description: "" },
  { name: "theme", description: "Change the theme" },
  { name: "think-back", description: "Your 2025 Claude Code Year in Review" },
  { name: "ultraplan", description: "" },
  { name: "upgrade", description: "Upgrade to Max for higher rate limits and more Opus" },
  { name: "usage", description: "Show plan usage limits" },
  { name: "version", description: "Print the version this session is running (not what autoupdate downloaded)" },
  { name: "vim", description: "Toggle between Vim and Normal editing modes" },
  { name: "voice", description: "Toggle voice mode" },
  { name: "web-setup", description: "Setup Claude Code on the web (requires connecting your GitHub account)" },
] as const
